from setuptools import setup, find_packages

setup(
  name = 'radir',
  packages = find_packages(exclude=[]),
  include_package_data = True,
  version = '0.1',
  description = 'RADIR',
  install_requires=[
    'beartype',
    'einops>=0.6',
    'ftfy',
    'regex',
    "XlsxWriter",
    "h5py",
    "matplotlib",
    "seaborn",
    "wilds",
    'ImageNetV2_pytorch @ git+https://github.com/modestyachts/ImageNetV2_pytorch.git',
    "click",
    "appdirs",
    "attr",
    "nltk",
    'transformers',
    'monai',
    'positional_encodings',
    'tensorboard',
    'nvidia-ml-py',
    'wandb',
    'torchvision',
      ],
)
